FROM chand1012/tensorflow:2.5.0

RUN mkdir /gpt-2
WORKDIR /gpt-2
ADD . /gpt-2
RUN pip3 install -r requirements.txt
RUN python3 download_model.py 124M
RUN python3 download_model.py 355M
# additional models would not build on the Pi
